"""
FastAPI Backend for Security Automation Platform (Fly.io Version)

This version runs entirely in simulator mode without Azure dependencies.
All data is generated by the SimulatorEngine for demo purposes.
"""

from fastapi import FastAPI, HTTPException, Depends, Header, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles
from fastapi.responses import FileResponse
from typing import Optional, List
from pydantic import BaseModel
import os
import json
from datetime import datetime
from dotenv import load_dotenv
from openai import OpenAI
from simulator import SimulatorEngine
from pathlib import Path

load_dotenv()

app = FastAPI(title="Security Automation API", version="2.0.0")

simulator = SimulatorEngine()

BEARER_TOKEN = os.getenv("BEARER_TOKEN", "your-secret-token-123")

@app.on_event("startup")
async def startup_event():
    simulator.start(interval_seconds=0.5)
    print(f"[Simulator] Running in SIMULATED mode - generating events in-process")

@app.on_event("shutdown")
async def shutdown_event():
    simulator.stop()

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

async def verify_token(authorization: Optional[str] = Header(None)):
    if not authorization:
        raise HTTPException(status_code=401, detail="Authorization header missing")
    
    try:
        scheme, token = authorization.split()
        if scheme.lower() != "bearer" or token != BEARER_TOKEN:
            raise HTTPException(status_code=401, detail="Invalid token")
    except ValueError:
        raise HTTPException(status_code=401, detail="Invalid authorization header")
    
    return token

def _get_simulated_data() -> dict:
    """Load simulated Azure data from JSON file."""
    import pathlib
    data_file = pathlib.Path(__file__).parent / "simulated_azure_data.json"
    with open(data_file, "r") as f:
        return json.load(f)

@app.get("/health")
async def health_check():
    return {
        "status": "healthy",
        "mode": "simulated",
        "simulator_events": len(simulator.events),
        "timestamp": datetime.utcnow().isoformat()
    }

# Azure API Endpoints (all return simulated data)
@app.get("/api/azure/aks/status", dependencies=[Depends(verify_token)])
async def get_aks_status():
    return _get_simulated_data()["get_aks_cluster_status"]

@app.get("/api/azure/pods/{namespace}", dependencies=[Depends(verify_token)])
async def list_pods(namespace: str):
    return _get_simulated_data().get(f"list_pods_{namespace}", {"namespace": namespace, "pods": [], "count": 0})

@app.get("/api/azure/pods/{namespace}/{pod_name}", dependencies=[Depends(verify_token)])
async def get_pod_details(namespace: str, pod_name: str):
    pods = _get_simulated_data().get("get_pod_details", {})
    for key, val in pods.items():
        if pod_name in key:
            return val
    return {"error": f"Pod '{pod_name}' not found"}

@app.get("/api/azure/resourcegroup/{rg_name}", dependencies=[Depends(verify_token)])
async def get_resource_group(rg_name: str):
    return _get_simulated_data()["get_resource_group_info"]

@app.get("/api/azure/resources/list", dependencies=[Depends(verify_token)])
async def list_resources():
    return _get_simulated_data()["list_all_resources"]

@app.get("/api/azure/appservice/{app_name}/status", dependencies=[Depends(verify_token)])
async def get_app_service_status(app_name: str):
    apps = _get_simulated_data().get("get_app_service_status", {})
    return apps.get(app_name, {"error": f"App service '{app_name}' not found"})

@app.get("/api/azure/functionapp/{function_name}/status", dependencies=[Depends(verify_token)])
async def get_function_app_status(function_name: str):
    fns = _get_simulated_data().get("get_function_app_status", {})
    return fns.get(function_name, {"error": f"Function app '{function_name}' not found"})

@app.get("/api/azure/storage/{account_name}/info", dependencies=[Depends(verify_token)])
async def get_storage_account_info(account_name: str):
    accts = _get_simulated_data().get("get_storage_account_info", {})
    return accts.get(account_name, {"error": f"Storage account '{account_name}' not found"})

@app.get("/api/azure/aks/nodepools", dependencies=[Depends(verify_token)])
async def get_node_pools():
    return _get_simulated_data()["get_aks_node_pools"]

@app.get("/api/azure/deployments/{namespace}", dependencies=[Depends(verify_token)])
async def get_deployments(namespace: str):
    return _get_simulated_data().get(f"get_deployments_{namespace}", {"namespace": namespace, "deployments": [], "count": 0})

@app.get("/api/azure/services/{namespace}", dependencies=[Depends(verify_token)])
async def get_services(namespace: str):
    return _get_simulated_data().get(f"get_services_{namespace}", {"namespace": namespace, "services": [], "count": 0})

@app.get("/api/azure/pods/{namespace}/{pod_name}/logs", dependencies=[Depends(verify_token)])
async def get_pod_logs(namespace: str, pod_name: str):
    logs = _get_simulated_data().get("get_pod_logs", {})
    for key, val in logs.items():
        if pod_name in key:
            return val
    return {"podName": pod_name, "namespace": namespace, "logs": ["No logs available for this pod in simulated mode."]}

@app.get("/api/azure/subscription/info", dependencies=[Depends(verify_token)])
async def get_subscription_info():
    return _get_simulated_data()["get_subscription_info"]

@app.get("/api/azure/costs/summary", dependencies=[Depends(verify_token)])
async def get_cost_analysis():
    return {
        "period": "Last 30 days",
        "totalCost": "$127.45",
        "breakdown": [
            {"service": "Azure Kubernetes Service", "cost": "$45.20"},
            {"service": "App Service", "cost": "$32.10"},
            {"service": "Function App", "cost": "$15.80"},
            {"service": "Storage Account", "cost": "$12.35"},
            {"service": "Other", "cost": "$22.00"}
        ],
        "note": "Cost data is simulated for demo purposes."
    }

# Kubernetes Monitor Endpoints
@app.get("/api/kubernetes/events", dependencies=[Depends(verify_token)])
async def get_kubernetes_events(limit: int = 100):
    return simulator.get_events(limit=limit)

@app.get("/api/kubernetes/stats", dependencies=[Depends(verify_token)])
async def get_kubernetes_stats():
    return simulator.get_stats()

@app.post("/api/kubernetes/pod-lifecycle/start", dependencies=[Depends(verify_token)])
async def pod_lifecycle_start(request: Request):
    return {"status": "acknowledged", "source": "simulated", "timestamp": datetime.utcnow().isoformat()}

@app.get("/api/kubernetes/applications", dependencies=[Depends(verify_token)])
async def get_kubernetes_applications():
    return simulator.get_applications()

# OpenAI Agent
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY", "")
openai_client = OpenAI(api_key=OPENAI_API_KEY) if OPENAI_API_KEY else None

AGENT_SYSTEM_PROMPT = """You are a read-only operations assistant for the Security Automation Platform. You support operations engineers who manage infrastructure and Kubernetes workloads.

You have access to simulated infrastructure data. Use the available tools to retrieve data when answering questions.

PERSONALITY:
- Be direct and professional
- Be thoughtful: consider what the user is really trying to accomplish
- Be patient: if a question is ambiguous, ask a brief clarifying question
- Be forthcoming: if you notice something unusual in the data, flag it even if the user didn't ask

RULES:
1. READ-ONLY: You can only retrieve and report information. You cannot modify, delete, or scale any resources.
2. Use the appropriate tools to fetch data. If a question spans multiple areas, call multiple tools.
3. Format responses clearly. Use bullet points or tables for lists.
4. If a tool call fails, explain what happened.
5. NEVER provide credentials, API keys, secrets, tokens, or connection strings.
6. If asked to perform a write operation, politely explain that you're read-only.

FORMAT:
- Use markdown for all responses
- Use **bold** for labels and important values
- Use markdown tables for tabular data
- Use bullet lists for key-value pairs and summaries

ENVIRONMENT:
- Kubernetes namespaces: hsps, star
- Running in simulated mode for demo purposes
"""

AGENT_TOOLS = [
    {
        "type": "function",
        "function": {
            "name": "get_aks_cluster_status",
            "description": "Get the current status and health of the Kubernetes cluster",
            "parameters": {"type": "object", "properties": {}, "required": []}
        }
    },
    {
        "type": "function",
        "function": {
            "name": "list_pods",
            "description": "List all pods running in a Kubernetes namespace (hsps or star)",
            "parameters": {
                "type": "object",
                "properties": {
                    "namespace": {"type": "string", "description": "Kubernetes namespace (hsps or star)", "enum": ["hsps", "star"]}
                },
                "required": ["namespace"]
            }
        }
    },
    {
        "type": "function",
        "function": {
            "name": "get_pod_details",
            "description": "Get detailed information about a specific pod",
            "parameters": {
                "type": "object",
                "properties": {
                    "namespace": {"type": "string", "description": "Kubernetes namespace"},
                    "pod_name": {"type": "string", "description": "Name of the pod"}
                },
                "required": ["namespace", "pod_name"]
            }
        }
    },
    {
        "type": "function",
        "function": {
            "name": "get_resource_group_info",
            "description": "Get information about the resource group",
            "parameters": {"type": "object", "properties": {}, "required": []}
        }
    },
    {
        "type": "function",
        "function": {
            "name": "list_all_resources",
            "description": "List all resources in the resource group",
            "parameters": {"type": "object", "properties": {}, "required": []}
        }
    },
    {
        "type": "function",
        "function": {
            "name": "get_cost_analysis",
            "description": "Get cost analysis summary for the last 30 days",
            "parameters": {"type": "object", "properties": {}, "required": []}
        }
    }
]

def _execute_tool_simulated(tool_name: str, arguments: dict) -> dict:
    """Execute a tool call using simulated data."""
    data = _get_simulated_data()

    if tool_name == "get_aks_cluster_status":
        return data["get_aks_cluster_status"]
    elif tool_name == "list_pods":
        ns = arguments.get("namespace", "hsps")
        return data.get(f"list_pods_{ns}", {"namespace": ns, "pods": [], "count": 0})
    elif tool_name == "get_pod_details":
        pod_name = arguments.get("pod_name", "")
        pod_details = data.get("get_pod_details", {})
        for key, val in pod_details.items():
            if pod_name in key:
                return val
        return {"error": f"Pod '{pod_name}' not found"}
    elif tool_name == "get_resource_group_info":
        return data["get_resource_group_info"]
    elif tool_name == "list_all_resources":
        return data["list_all_resources"]
    elif tool_name == "get_cost_analysis":
        return data.get("get_cost_analysis", {"period": "Last 30 days", "totalCost": "$127.45", "note": "Simulated data"})
    else:
        return {"error": f"Unknown tool: {tool_name}"}

async def execute_tool(tool_name: str, arguments: dict) -> dict:
    """Execute a tool call and return the result."""
    try:
        return _execute_tool_simulated(tool_name, arguments)
    except Exception as e:
        return {"error": str(e)}

class ChatMessage(BaseModel):
    role: str
    content: str

class AgentChatRequest(BaseModel):
    message: str
    history: List[ChatMessage] = []

class AgentChatResponse(BaseModel):
    response: str
    tool_calls_made: List[str] = []

@app.post("/api/agent/chat", dependencies=[Depends(verify_token)])
async def agent_chat(request: AgentChatRequest):
    """AI Agent endpoint using OpenAI function calling."""
    if not openai_client:
        raise HTTPException(status_code=500, detail="OpenAI API key not configured. Set OPENAI_API_KEY in environment.")

    messages = [{"role": "system", "content": AGENT_SYSTEM_PROMPT}]
    
    for msg in request.history[-20:]:
        messages.append({"role": msg.role, "content": msg.content})
    
    messages.append({"role": "user", "content": request.message})

    tool_calls_made = []

    try:
        response = openai_client.chat.completions.create(
            model="gpt-4o-mini",
            messages=messages,
            tools=AGENT_TOOLS,
            tool_choice="auto",
            max_tokens=2000,
            temperature=0.3
        )

        assistant_message = response.choices[0].message

        max_iterations = 5
        iteration = 0

        while assistant_message.tool_calls and iteration < max_iterations:
            iteration += 1
            
            messages.append(assistant_message)

            for tool_call in assistant_message.tool_calls:
                fn_name = tool_call.function.name
                fn_args = json.loads(tool_call.function.arguments)
                
                tool_calls_made.append(fn_name)
                
                result = await execute_tool(fn_name, fn_args)
                
                messages.append({
                    "role": "tool",
                    "tool_call_id": tool_call.id,
                    "content": json.dumps(result)
                })

            response = openai_client.chat.completions.create(
                model="gpt-4o-mini",
                messages=messages,
                tools=AGENT_TOOLS,
                tool_choice="auto",
                max_tokens=2000,
                temperature=0.3
            )

            assistant_message = response.choices[0].message

        return AgentChatResponse(
            response=assistant_message.content or "I wasn't able to generate a response. Please try again.",
            tool_calls_made=tool_calls_made
        )

    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Agent error: {str(e)}")

# Mount static files for the UI
ui_dist_path = Path("/app/ui/dist")
if ui_dist_path.exists():
    app.mount("/assets", StaticFiles(directory=str(ui_dist_path / "assets")), name="assets")
    
    @app.get("/")
    async def serve_spa():
        return FileResponse(str(ui_dist_path / "index.html"))
    
    # Catch-all route for SPA - must be last
    @app.api_route("/{full_path:path}", methods=["GET"], include_in_schema=False)
    async def catch_all(full_path: str):
        # Serve static files or SPA for non-API routes
        file_path = ui_dist_path / full_path
        if file_path.exists() and file_path.is_file():
            return FileResponse(str(file_path))
        # For SPA routing, return index.html for non-existent paths
        return FileResponse(str(ui_dist_path / "index.html"))

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
